urlaubsmanager-web/src/main/java/at/gv/brz/trainee/um/controller/UrlaubAntraegeController.java
package at.gv.brz.trainee.um.controller;

import static at.gv.brz.trainee.um.utility.Constants.NAVIGATION_ON_FAILURE;
import static at.gv.brz.trainee.um.utility.Constants.NAVIGATION_ON_SUCCESS;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.stream.Collectors;

import javax.faces.model.ListDataModel;

import at.gv.brz.trainee.um.exception.ServiceException;
import at.gv.brz.trainee.um.model.Urlaub;
import at.gv.brz.trainee.um.model.User;
import at.gv.brz.trainee.um.model.VTeam;
import at.gv.brz.trainee.um.service.impl.UrlaubServiceJPA;

/**
 * Kontrolliert den Antrag der Urlaubserstellung.
 * 
 * @author toemoes
 *
 */
public class UrlaubAntraegeController implements Serializable {

    private static final long serialVersionUID = 1L;

    private UrlaubServiceJPA urlaubService;

    private ListDataModel<Urlaub> urlaube;

    private Urlaub currentUrlaub;

    private User currentUser;

    private VTeam currentVTeam;

    private SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");

    private boolean genehmigt;

    private boolean abgelehnt;

    public String showUrlaubAntraege() {
        genehmigt = false;
        abgelehnt = false;
        return NAVIGATION_ON_SUCCESS;
    }

    /**
     * Genehmigt den Urlaubsantrag.
     * 
     * @return Fehler oder Erfolg Text als String.
     */
    public String genehmigen() {
        genehmigt = false;
        abgelehnt = false;
        try {
            urlaubService.setUrlaubgnehmigt(currentUrlaub);
            genehmigt = true;
        } catch (ServiceException e) {
            e.printStackTrace();
            return NAVIGATION_ON_FAILURE;
        }
        return NAVIGATION_ON_SUCCESS;
    }

    public void urlaubFuerDialog() {
        currentUrlaub = urlaube.getRowData();
    }

    /**
     * Lehnt den Urlaubsantrag ab.
     * 
     * @return success oder failure as String
     */
    public String ablehnen() {
        genehmigt = false;
        abgelehnt = false;
        try {
            urlaubService.setUrlaubabgelehnt(currentUrlaub);
            abgelehnt = true;
        } catch (ServiceException e) {
            e.printStackTrace();
            return NAVIGATION_ON_FAILURE;
        }
        return NAVIGATION_ON_SUCCESS;
    }

    /**
     * Liefert das Urlaub Start Date formattiert zurück.
     * 
     * @return Formattierte Date als String.
     * @autor gaalcs
     */
    public String getStartDate() {
        return dateFormat.format(currentUrlaub.getStartDatum());
    }

    /**
     * Liefert das Urlaub End Date formattiert zurück.
     * 
     * @return Formattierte Date als String.
     * @autor gaalcs
     */
    public String getEndDate() {
        return dateFormat.format(currentUrlaub.getEndDatum());
    }

    /**
     * Überprüft, ob sich die Daten in einer Liste überscheiden. Es wird jedes Datum einer Reihe einzeln überprüft
     * und mit den Daten der Liste verglichen.
     * 
     * @return true, wenn das Datum überschneidet ein anderes Datum.
     * @throws ServiceException falls etwas mit Service nicht passt.
     * @author gaalcs
     */
    public boolean isUrlaubUeberschneidet() throws ServiceException {
        Urlaub urlaub = urlaube.getRowData();
        long urlaubStartDatum = urlaub.getStartDatum().getTime();
        long urlaubEndDatum = urlaub.getEndDatum().getTime();
        List<Urlaub> hilfliste = getOffeneUrlaubeSortiertByDate();
        for (int i = 0; i < hilfliste.size(); i++) {
            if (urlaub.getId() == hilfliste.get(i).getId()) {
                continue;
            }
            long listStartDatum = hilfliste.get(i).getStartDatum().getTime();
            long listEndDatum = hilfliste.get(i).getEndDatum().getTime();
            if ((urlaubStartDatum >= listStartDatum && urlaubStartDatum <= listEndDatum)
                || (urlaubEndDatum >= listStartDatum && urlaubEndDatum <= listEndDatum)
                || (urlaubStartDatum < listStartDatum && urlaubEndDatum > listEndDatum)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Holt eine Urlaubliste nach VTeam und User, wenn das Status OFFEN ist von der Datenbank und sortiert die Liste
     * nach Start Datum.
     * 
     * @return Eine Liste von Urlaube nach Star Datum sortiert.
     * @throws ServiceException falls etwas mit Service nicht passt.
     * @author gaalcs
     */
    public List<Urlaub> getOffeneUrlaubeSortiertByDate() throws ServiceException {
        List<Urlaub> urlaublist = urlaubService.getUrlaubListOffen(currentVTeam, currentUser);
        return urlaublist.stream().sorted((u1, u2) -> u1.getStartDatum().compareTo(u2.getStartDatum()))
                         .collect(Collectors.toList());
    }

    public UrlaubServiceJPA getUrlaubService() {
        return urlaubService;
    }

    public void setUrlaubService(UrlaubServiceJPA urlaubService) {
        this.urlaubService = urlaubService;
    }

    public ListDataModel<Urlaub> getUrlaube() {
        try {
            urlaube = new ListDataModel<>(getOffeneUrlaubeSortiertByDate());

        } catch (ServiceException e) {
            e.printStackTrace();
        }
        return urlaube;
    }

    public void setUrlaube(ListDataModel<Urlaub> urlaube) {
        this.urlaube = urlaube;
    }

    public Urlaub getCurrentUrlaub() {
        return currentUrlaub;
    }

    public void setCurrentUrlaub(Urlaub currentUrlaub) {
        this.currentUrlaub = currentUrlaub;
    }

    public User getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(User currentUser) {
        this.currentUser = currentUser;
    }

    public VTeam getCurrentVTeam() {
        return currentVTeam;
    }

    public void setCurrentVTeam(VTeam currentVTeam) {
        this.currentVTeam = currentVTeam;
    }

    public boolean isGenehmigt() {
        return genehmigt;
    }

    public void setGenehmigt(boolean genehmigt) {
        this.genehmigt = genehmigt;
    }

    public boolean isAbgelehnt() {
        return abgelehnt;
    }

    public void setAbgelehnt(boolean abgelehnt) {
        this.abgelehnt = abgelehnt;
    }

}

urlaubsmanager-web/src/main/java/at/gv/brz/trainee/um/controller/UrlaubController.java
package at.gv.brz.trainee.um.controller;

import static at.gv.brz.trainee.um.utility.Constants.NAVIGATION_ON_FAILURE;
import static at.gv.brz.trainee.um.utility.Constants.NAVIGATION_ON_SUCCESS;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import javax.faces.model.ListDataModel;

import at.gv.brz.trainee.um.exception.ServiceException;
import at.gv.brz.trainee.um.model.Urlaub;
import at.gv.brz.trainee.um.model.User;
import at.gv.brz.trainee.um.model.VTeam;
import at.gv.brz.trainee.um.model.enums.Status;
import at.gv.brz.trainee.um.service.UrlaubService;
import at.gv.brz.trainee.um.service.impl.UrlaubServiceJPA;

/**
 * Diese Klasse enthält Methoden zur Verarbeitung von Anforderungen zum Speichern, Aktualisieren, Löschen und
 * Auflisten von Urlauben.
 * 
 * @author muradd, Kommentaruebersetzung: janua
 *
 */
public class UrlaubController implements Serializable {
    private static final long serialVersionUID = 1L;

    private UrlaubServiceJPA urlaubService;

    private Urlaub currentUrlaub = new Urlaub();

    private VTeam currentVTeam = new VTeam();

    private User currentUser;

    private ListDataModel<Urlaub> urlaube;

    /**
     * Methode: ruft add() Methode von UrlaubsService auf. Verknuepft aktuellen Urlaub mit aktuellem Nutzer, fuegt den
     * aktuellen Urlaub hinzu.
     * 
     * @return NAVIGATION_ON_SUCCESS wenn add() funktioniert, sonst NAVIGATION_ON_FAILURE
     **/
    public String save() {
        currentUrlaub.setUser(currentUser);
        try {
            urlaubService.add(currentUrlaub);
        } catch (ServiceException se) {
            se.printStackTrace();
            return NAVIGATION_ON_FAILURE;
        }
        return NAVIGATION_ON_SUCCESS;
    }

    /**
     * Methode: ruft upate() Methode von UrlaubService auf. Aktualisiert den aktuellen Urlaub.
     *
     * @return NAVIGATION_ON_SUCCESS wenn update() funktioniert, sonst NAVIGATION_ON_FAILURE
     **/
    public String update() {
        try {
            urlaubService.update(currentUrlaub);
        } catch (ServiceException se) {
            se.printStackTrace();
            return NAVIGATION_ON_FAILURE;
        }

        return NAVIGATION_ON_SUCCESS;
    }

    /**
     * Methode: verknüpft den aktuellen Urlaub mit der korrekten Zeile.
     *
     * @return NAVIGATION_ON_SUCCESS wenn showEdit() funktioniert, sonst NAVIGATION_ON_FAILURE
     **/
    public String showEdit() {
        currentUrlaub = urlaube.getRowData();
        return NAVIGATION_ON_SUCCESS;
    }

    /**
     * Methode: ruft Methode delete() von Urlaubsservice auf. Diese setzt Variable deleted von Urlaub auf true damit
     * Urlaub nicht komplett aus der Datenbank geloescht wird. Verknuepft den aktuellen Urlaub mit der korrekten Zeile.
     * Geloeschte Urlaube werden in der Urlaubsliste nicht mehr angezeigt.
     * 
     * @return NAVIGATION_ON_SUCCESS wenn delete() funktioniert, sonst NAVIGATION_ON_FAILURE
     **/
    public String delete() {
        try {
            urlaubService.delete(currentUrlaub.getId());
        } catch (ServiceException se) {
            se.printStackTrace();
            return NAVIGATION_ON_FAILURE;
        }

        return NAVIGATION_ON_SUCCESS;
    }

    /**
     * Methode: setzt aktuellen Urlaub zurueck.
     *
     * @return NAVIGATION_ON_SUCCESS
     **/
    public String showInsert() {
        currentUrlaub = new Urlaub();
        return NAVIGATION_ON_SUCCESS;
    }

    /**
     * Der Urlaub wird für das Pop-Up Fenster gesetzt, um in der Delete Methode verwendet zu werden.
     */
    public void urlaubForDialog() {
        currentUrlaub = urlaube.getRowData();
        setCurrentUrlaub(currentUrlaub);
    }

    /**
     * Überprüft, ob sich die Daten in einer Liste überscheiden. Es wird jedes Datum einer Reihe einzeln überprüft
     * und mit den Daten der Liste verglichen. <br>
     * 
     * @return true, wenn das Datum überschneidet ein anderes Datum.
     * @throws ServiceException
     *             falls etwas mit der Service nicht stimmt.
     * @author gaalcs, Felix, Daniel
     */
    public boolean isUrlaubUeberschneidet() throws ServiceException {
        Urlaub urlaub = urlaube.getRowData();
        long urlaubStartDatum = urlaub.getStartDatum().getTime();
        long urlaubEndDatum = urlaub.getEndDatum().getTime();
        List<Urlaub> hilfliste = getUrlaubeSortiertByDate();
        for (int i = 0; i < hilfliste.size(); i++) {
            if (urlaub.getId() == hilfliste.get(i).getId()) {
                continue;
            }
            long listStartDatum = hilfliste.get(i).getStartDatum().getTime();
            long listEndDatum = hilfliste.get(i).getEndDatum().getTime();
            if ((urlaubStartDatum >= listStartDatum && urlaubStartDatum <= listEndDatum)
                || (urlaubEndDatum >= listStartDatum && urlaubEndDatum <= listEndDatum)
                || (urlaubStartDatum < listStartDatum && urlaubEndDatum > listEndDatum)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Vergleichet den aktuellen User von DataTable Row mit dem currentUser.
     * 
     * @return true, wenn der User gleich ist mit dem currentUser.
     * @author gaalcs
     */
    public boolean isUserCurrentUser() {
        User user = urlaube.getRowData().getUser();
        if (user.getId() == currentUser.getId()) {
            return true;
        }
        return false;
    }

    /**
     * Vergleicht User von DataTable Row mit currentUser und prüft, ob Status von Urlaub Offen ist.
     * 
     * @return true, wenn User gleich dem currentUser ist und der Urlaub Status OFFEN hat
     * @author konrathi
     */
    public boolean isUserCurrentUserWithStatusOffen() {
        Urlaub urlaub = urlaube.getRowData();

        if (urlaub.getUser().getId() == currentUser.getId() && urlaub.getStatus().equals(Status.OFFEN)) {
            return true;
        }
        return false;
    }

    /**
     * Holt eine Urlaubliste nach VTeam Id von der Datenbank und sortiert die Liste nach Start Datum.
     * 
     * @return Eine Liste von Urlaube nach Star Datum sortiert.
     * @throws ServiceException
     *             falls etwas mit der Service nicht stimmt.
     * @author gaalcs
     */
    public List<Urlaub> getUrlaubeSortiertByDate() throws ServiceException {
        List<Urlaub> urlaublist = urlaubService.getUrlaubListByVTeam(currentVTeam.getId());
        return urlaublist.stream().sorted((u1, u2) -> u1.getStartDatum().compareTo(u2.getStartDatum()))
                         .collect(Collectors.toList());
    }

    /*
     * ***************** Constructor **************************
     */

    public UrlaubController() {
        super();
    }

    /*
     * *****************Getters & Setters***********************
     */

    public Urlaub getCurrentUrlaub() {
        return currentUrlaub;
    }

    public void setCurrentUrlaub(Urlaub currentUrlaub) {
        this.currentUrlaub = currentUrlaub;
    }

    public ListDataModel<Urlaub> getUrlaube() throws ServiceException {
        this.urlaube = new ListDataModel<>(getUrlaubeSortiertByDate());
        return this.urlaube;
    }

    public void setUrlaube(ListDataModel<Urlaub> urlaube) {
        this.urlaube = urlaube;
    }

    public UrlaubService getUrlaubService() {
        return urlaubService;
    }

    public void setUrlaubService(UrlaubServiceJPA urlaubService) {
        this.urlaubService = urlaubService;
    }

    public VTeam getCurrentVTeam() {
        return currentVTeam;
    }

    public void setCurrentVTeam(VTeam currentVTeam) {
        this.currentVTeam = currentVTeam;
    }

    public User getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(User currentUser) {
        this.currentUser = currentUser;
    }

    public List<Status> getStatus() {
        List<Status> status = new ArrayList<>();
        status.add(Status.OFFEN);
        status.add(Status.GENEHMIGT);
        status.add(Status.ABGELEHNT);
        return status;
    }
}

urlaubsmanager-web/src/main/webapp/_failure.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html">

<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<link rel="stylesheet"
		href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>

	<title>#{msg.failure_title}</title>
</h:head>
<body>
	<ui:include src="_nav.xhtml" />
	<h1>Ohje! Da ist leider etwas schief gelaufen!</h1>
	
	<ui:include src="_footer.xhtml" />
</body>
</html>

urlaubsmanager-web/src/main/webapp/_footer.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

	<div class="ui-g-12 layout-footer">
		<div class="footer-center" >
			<div class="footer-info-center">
				Copyright © BRZ GmbH, JAVA Traineeprogram September 2019 </div>
		</div>
	</div>
</html>

urlaubsmanager-web/src/main/webapp/urlaubAntraege.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet"
		href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
	<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link rel="stylesheet" href="resources/style.css" />
	<title>#{msg.urlaubAntraege_titel}</title>
</h:head>

<body>
	<ui:include src="_nav.xhtml" />
	<div class="container">
		<h1>#{msg.urlaubAntraege_head} -
			#{urlaubAntraegeController.currentVTeam.name}</h1>

		<f:view>
			<h:form>

				<h:outputText rendered="#{urlaubAntraegeController.genehmigt}"
					style="color:#1c750c"
					value="#{msg.urlaubAntraege_Urlaub} #{msg.urlaubAntraege_von} #{urlaubAntraegeController.currentUrlaub.user.vorname} #{urlaubAntraegeController.currentUrlaub.user.nachname} #{msg.urlaubAntraege_von} #{urlaubAntraegeController.startDate} #{msg.urlaubAntraege_bis} #{urlaubAntraegeController.endDate} #{msg.urlaubAntraege_genehmigt}"></h:outputText>
				<h:outputText rendered="#{urlaubAntraegeController.abgelehnt}"
					style="color:#ff0026"
					value="#{msg.urlaubAntraege_Urlaub} #{msg.urlaubAntraege_von} #{urlaubAntraegeController.currentUrlaub.user.vorname} #{urlaubAntraegeController.currentUrlaub.user.nachname} #{msg.urlaubAntraege_von} #{urlaubAntraegeController.startDate} #{msg.urlaubAntraege_bis} #{urlaubAntraegeController.endDate} #{msg.urlaubAntraege_abgelehnt}"></h:outputText>

				<p:dataTable value="#{urlaubAntraegeController.urlaube}" var="u"
					styleClass="table table-striped table-bordered"
					emptyMessage="Keine Urlaube gefunden."
					rowStyleClass="#{urlaubAntraegeController.urlaubUeberschneidet ? 'ueberschneidung' : null}">

					<p:column headerText="#{msg.urlaubListe_name}">
						#{u.user.vorname} #{u.user.nachname}
					</p:column>

					<p:column headerText="#{msg.urlaubListe_urlaub}">
						<h:outputText value="#{u.startDatum}">
							<f:convertDateTime pattern="dd.MM.yyyy" timeZone="Europe/Vienna" />
						</h:outputText>
						-
						<h:outputText value="#{u.endDatum}">
							<f:convertDateTime pattern="dd.MM.yyyy" timeZone="Europe/Vienna" />
						</h:outputText>
					</p:column>

					<p:column>
						<f:facet name="header">
							#{msg.urlaubListe_kommentar}
						</f:facet>
						#{u.kommentar}
					</p:column>

					<p:column>
						<f:facet name="header">#{msg.urlaubAntragPM_status}</f:facet>
						<div class="divBtn">
							<p:commandButton class="btn"
								onclick="PF('dlgGenehmigen').show();" id="genehmigen1"
								title="Genehmigen" icon="fa fa-check"
								action="#{urlaubAntraegeController.urlaubFuerDialog}" />


							<p:commandButton class="btn" onclick="PF('dlgAblehnen').show();"
								id="ablehnen1" title="Ablehnen" icon="fa fa-ban"
								action="#{urlaubAntraegeController.urlaubFuerDialog}" />
						</div>

					</p:column>

				</p:dataTable>

				<h:panelGrid columns="1">
					<p:commandButton styleClass="btnNormal" action="cancel" value="Zurück zu meinen Teams" />
				</h:panelGrid>

				<p:dialog header="Sind Sie sicher?" widgetVar="dlgGenehmigen"
					closeOnEscape="true" resizable="false" modal="true">
					<p:commandButton action="#{urlaubAntraegeController.genehmigen}"
						id="dlgGenehmigen" value="Ja" ajax="false" />
					<p:commandButton value="Nein" onclick="dlgGenehmigen.hide()" action="#{urlaubAntraegeController.showUrlaubAntraege}" />
				</p:dialog>

				<p:dialog header="Sind Sie sicher?" widgetVar="dlgAblehnen"
					modal="true" closeOnEscape="true" resizable="false">
					<p:commandButton action="#{urlaubAntraegeController.ablehnen}"
						id="dlgAblehnen" value="Ja" ajax="false" />
					<p:commandButton value="Nein" onclick="dlgAblehnen.hide()" action="#{urlaubAntraegeController.showUrlaubAntraege}" />
				</p:dialog>

			</h:form>
		</f:view>
	</div>

	<ui:include src="_footer.xhtml" />

</body>

</html>

urlaubsmanager-web/src/main/webapp/urlaubListe.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet"
		href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
	<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link rel="stylesheet" href="resources/style.css" />
	<title>#{msg.urlaubListe_titel}</title>
</h:head>

<body>
	<ui:include src="_nav.xhtml" />
	<div class="container">
		<h1>#{msg.urlaubListe} - #{urlaubController.currentVTeam.name}</h1>
		<f:view>
			<h:form>
				<p:dataTable value="#{urlaubController.urlaube}" var="u"
					emptyMessage="Keine Urlaube gefunden."
					styleClass="table table-striped table-bordered" scrollable="true"
					scrollHeight="500"
					rowStyleClass="#{urlaubController.urlaubUeberschneidet ? 'ueberschneidung' : null}"
					widgetVar="urlaubTable">

					<p:column headerText="#{msg.urlaubListe_name}">
						<h:outputText
							styleClass="#{urlaubController.userCurrentUser ? 'userNameBold' : null}"
							value="#{u.user.vorname} #{u.user.nachname}" />
					</p:column>

					<p:column headerText="#{msg.urlaubListe_urlaub}">
						<h:outputText value="#{u.startDatum}">
							<f:convertDateTime pattern="dd.MM.yyyy" timeZone="Europe/Vienna" />
						</h:outputText>
						<h:outputText value=" - " />
						<h:outputText value="#{u.endDatum}">
							<f:convertDateTime pattern="dd.MM.yyyy" timeZone="Europe/Vienna" />
						</h:outputText>
					</p:column>

					<p:column headerText="#{msg.urlaubListe_status}">
						<h:outputText value="#{u.status}" />
					</p:column>

					<p:column>
						<f:facet name="header">
							#{msg.urlaubListe_kommentar}
						</f:facet>
						<h:outputText value="#{u.kommentar}" />
					</p:column>

					<p:column>
						<f:facet name="header">#{msg.header_edit}</f:facet>
						<div class="divBtn">
							<p:commandButton
								styleClass="#{urlaubController.userCurrentUserWithStatusOffen ? null : 'btnHidden'} btnIcon"
								action="#{urlaubController.showEdit}" id="edit"
								title="Bearbeiten" icon="fa fa-pencil" />
						</div>
					</p:column>

					<p:column>
						<f:facet name="header">#{msg.header_delete}</f:facet>
						<div class="divBtn">
							<p:commandButton
								styleClass="#{urlaubController.userCurrentUserWithStatusOffen ? null : 'btnHidden'} btnIcon"
								onclick="PF('dlgLoeschen').show();" id="delete1" title="Löschen"
								icon="fa fa-trash" action="#{urlaubController.urlaubForDialog}" />
						</div>
					</p:column>

				</p:dataTable>

				<h:panelGrid columns="2">
					<p:commandButton styleClass="btnSpecial"
						action="#{urlaubController.showInsert}"
						value="#{msg.button_newUrlaub}" />

					<p:commandButton styleClass="btnNormal" action="backToMeineVTeams"
						value="#{msg.button_zuVT}" />
				</h:panelGrid>

				<p:dialog header="Sind Sie sicher?" widgetVar="dlgLoeschen"
					modal="true" closeOnEscape="true" resizable="false">
					<p:commandButton action="#{urlaubController.delete}" id="dlgDelete"
						value="Ja" />
					<p:commandButton onclick="PF('dlgLoeschen').hide();"
						id="dlgLoeschen" value="Nein" />
				</p:dialog>

			</h:form>
		</f:view>
	</div>

	<ui:include src="_footer.xhtml" />

</body>
</html>